Back to default GCC on Amazon Linux 2.

diff --git a/src/libffi/chevahbs b/src/libffi/chevahbs
--- a/src/libffi/chevahbs
+++ b/src/libffi/chevahbs
@@ -22,7 +22,6 @@ chevahbs_getsources() {
 chevahbs_configure() {
     # To properly quote multiple options, this is a Bash array.
     CONF_OPTS=(--disable-shared --enable-static)
-    CFLAGS="$CFLAGS -fPIC"
     execute ./configure --prefix="" "${CONF_OPTS[@]}"
 }
 
@@ -33,6 +32,15 @@ chevahbs_compile() {
 
 # This requires DejaGnu to actually do the tests.
 chevahbs_try() {
+    # Tests fail on Amazon 2: https://github.com/libffi/libffi/issues/785.
+    if [ "$OS" = "linux" ]; then
+        if [ -f /etc/os-release ]; then
+            if grep -q ^'PRETTY_NAME="Amazon Linux 2"'$ /etc/os-release; then
+                (>&2 echo -e "\tSkipping libffi tests on Amazon Linux 2.")
+                return
+            fi
+        fi
+    fi
     execute "${MAKE_CMD[@]}" check
 }
 
