Enable upstream Python tests. (#45)
* Try upstream Python tests once more.

* Exit for Python tests errors.

* Try fixing test_cppext.

* Try fixing locale-related tests on Alpine.

* Do not run Python's upstream tests on Alpine for now.

* Try fixing the Python test failures on macOS.

* Stop trying harder to run upstream Python tests on macOS.

* Actually execute the Shellcheck tests again.

* Use a hardcoded filename for Bash arrays too.

* Always use the more compatible way of appending to a Bash array.

* Use dedicated sections when testing after compiling.

* Do not run libffi upstream tests on Amazon Linux 2.

* Cosmetic GHA output improvements.

* One more cosmetic GHA output improvement.

* One final cosmetic change.

diff --git a/src/Python/chevahbs b/src/Python/chevahbs
--- a/src/Python/chevahbs
+++ b/src/Python/chevahbs
@@ -8,7 +8,7 @@
 # The relative paths work in both src/blabla and build/blabla.
 source ../../functions.sh
 source ../../functions_build.sh
-source ../../"$BUILD_ENV_ARRAYS_FILE"
+source ../../BUILD_ENV_ARRAYS
 
 
 chevahbs_getsources() {
@@ -79,22 +79,30 @@ chevahbs_configure() {
 
 chevahbs_compile() {
     execute "${MAKE_CMD[@]}"
-    # FIXME:12: Enable Python's own tests again.
-    # Don't use execute below, some tests might fail innocuously.
-    # execute "${MAKE_CMD[@]}" test
+}
+
+chevahbs_try() {
+    if [ "$OS" = "macos" ]; then
+        # Extra CA certs needed to pass test_cppext/test_distutils, and included
+        # Mac/BuildScript/resources/install_certificates.command fix is broken.
+        (>&2 echo -e "\tNot running Python upstream tests on macOS.")
+    elif [ "$OS" = "linux_musl" ]; then
+        # Locales not supported on Alpine 3.12, failing locale-related tests.
+        (>&2 echo -e "\tNot running Python upstream tests on musl-based Linux.")
+    else
+        execute "${MAKE_CMD[@]}" test
+    fi
 }
 
 
-chevahbs_install() {
-    case "$OS" in
-        alpine*)
-            # EMUTRAMP required for full functionality under a grsec kernel.
-            # Don't use "paxmark", file attributes will be lost when tar'ed.
-            # Needed with non-grsec kernels as well, otherwise PAM-related
-            # compat tests crash with signal 11 (last tested on Alpine 3.12).
-            execute paxctl -cE python
-            ;;
-    esac
+chevahbs_cp() {
+    if [ "$OS" = "linux_musl" ]; then
+        # EMUTRAMP required for full functionality under a grsec kernel.
+        # Don't use "paxmark", file attributes will be lost when tar'ed.
+        # Needed with non-grsec kernels as well, otherwise PAM-related
+        # compat tests crash with signal 11 (last tested on Alpine 3.12).
+        execute paxctl -cE python
+    fi
 
     execute "${MAKE_CMD[@]}" install
 }
diff --git a/src/libffi/chevahbs b/src/libffi/chevahbs
--- a/src/libffi/chevahbs
+++ b/src/libffi/chevahbs
@@ -6,7 +6,7 @@
 # The relative paths work in both src/blabla and build/blabla.
 source ../../functions.sh
 source ../../functions_build.sh
-source ../../"$BUILD_ENV_ARRAYS_FILE"
+source ../../"BUILD_ENV_ARRAYS"
 
 
 chevahbs_getsources() {
@@ -30,8 +30,22 @@ chevahbs_compile() {
     execute "${MAKE_CMD[@]}"
 }
 
+# This requires DejaGnu to actually do the tests.
+chevahbs_try() {
+    # Tests fail on Amazon 2: https://github.com/libffi/libffi/issues/785.
+    if [ "$OS" = "linux" ]; then
+        if [ -f /etc/os-release ]; then
+            if grep -q ^'PRETTY_NAME="Amazon Linux 2"'$ /etc/os-release; then
+                (>&2 echo -e "\tSkipping libffi tests on Amazon Linux 2.")
+                return
+            fi
+        fi
+    fi
+    execute "${MAKE_CMD[@]}" check
+}
 
-chevahbs_install() {
+
+chevahbs_cp() {
     case "$OS" in
         linux*)
             echo "Installing manually to avoid messing with a lib64/ sub-dir:"
